### ISSUE TITLE
Documentation for checked operations says "instead of wrapping around on underflow"

### ISSUE THREAD

**Issue by kryptan** [rust-num/num#107]
Documentation for `CheckedAdd`, `CheckedDiv`, `CheckedMul`, `CheckedSub` says: Performs operation that returns `None` instead of wrapping around on underflow.

"instead of wrapping around on underflow" sounds like wrapping on overflow is the default behaviour but it is not.

P.S. there are traits for checked and saturating operations but no trait for wrapped operations, why?

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-traits#13
