### ISSUE TITLE
Complex type is lacking mathematical functions.

### ISSUE THREAD

**Issue by wrieger93** [rust-num/num#111]
Looking at popular complex number libraries in other languages ([C++](http://www.cplusplus.com/reference/complex/), [Python](https://docs.python.org/3/library/cmath.html), [Java](https://commons.apache.org/proper/commons-math/apidocs/org/apache/commons/math3/complex/Complex.html), [C#](https://msdn.microsoft.com/en-us/library/system.numerics.complex.aspx), etc), all of them offer several mathematical functions that Rust currently lacks. It'd be nice if Rust supported at least the following types of functions on complex numbers:
- Exponential and logarithmic (exp, ln)
- Power (z^c) and square root (sqrt)
- Trigonometric and their inverses (sin, cos, tan, arcsin, arccos, arctan)
- Hyperbolic and their inverses (sinh, cosh, tanh, arcsinh, arccosh, arctanh)

Most of the formulas for these functions are not very hard to implement, but a possible complication is how to deal with NaN/infinite values.

Some of the functions, such as ln and the inverse trig functions, are multiple valued and a principal branch and corresponding branch cut would need to be chosen. There is a general consensus as to what the principal values should be (for details, see [here](https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node129.html) and [here](https://people.freebsd.org/~das/kahan86branch.pdf)) so I don't think this is an issue.

**Comment by cuviper** [comment]
I believe `Complex` does have all these now.  If you need more, please open an issue here:
https://github.com/rust-num/num-complex/issues
