### ISSUE TITLE
Provide {Add,Mul,Sub,Div}<&'b T> for &'a Complex<T>

### ISSUE THREAD

**Issue by SuperFluffy** [rust-num/num#116]
At the moment, the traits `Add`, `Mul`, `Sub`, and `Div` corresponding to their respective binary operations are implemented only for `Complex<T>`, see for example [here](https://github.com/rust-lang/num/blob/master/src/complex.rs#L153):

    impl<'a, 'b, T: Clone + Num> Add<&'b Complex<T>> for &'a Complex<T> {
        type Output = Complex<T>;
    
        #[inline]
        fn add(self, other: &Complex<T>) -> Complex<T> {
            Complex::new(self.re.clone() + other.re.clone(),
                         self.im.clone() + other.im.clone())
        }
    }

It would be great if we'd also have the same operations for just their types `T`, so that for example `(0.0+1.0i) + 1.0 = 1.0 + 1.0i`, or instead of having to use `scale()` as in `let myc = Complex<T> { re: 1.0, im: 1.0}; myc.scale(2.0)`, we could simply say `myc * 2.0`. The `Add` trait would then look like:

    impl<'a, 'b, T: Clone + Num> Add<&'b T> for &'a Complex<T> {
        type Output = Complex<T>;
    
        #[inline]
        fn add(self, other: &Complex<T>) -> Complex<T> {
            Complex::new(self.re.clone() + other.clone(), self.im.clone())
        }
    }

**Comment by cuviper** [comment]
Closed by #125; let us know if anything is missing!
