### ISSUE TITLE
next_after for Float

### ISSUE THREAD

**Issue by carlosliam** [rust-num/num#118]
I'd appreciate a `next_after()` function definition for the Float trait based on the (currently unstable) `{f32,f64}::next_after()`, defined [here](https://doc.rust-lang.org/std/primitive.f32.html#method.next_after).

**Comment by SirVer** [comment]
+1. Is there another crate that has this already?

**Comment by cuviper** [comment]
Upstream deprecated `next_after`: rust-lang/rust#27752.

**Comment by vks** [comment]
Note the reason for deprecation:
> never really came to fruition and easily implementable outside the standard library

This implies that the fact it was deprecated should not preclude it being implemented in `num`.

**Comment by Stargateur** [comment]
Why not include it to num ?
