### ISSUE TITLE
Casting floats to integers does not check overflow

### ISSUE THREAD

**Issue by photino** [rust-num/num#119]
The following code 

``` rust
num::cast::<f64, i32>(1.0e+123f64)
```

will return

``` rust
Some(-2147483648)
```

instead of `None`.

**Comment by cuviper** [comment]
I think the root problem is `impl_to_primitive_float`, which just typecasts to integers with `as`.

**Comment by apopiak** [comment]
I'd like to try this one.

**Comment by cuviper** [comment]
@apopiak go for it!

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-traits#12
