### ISSUE TITLE
Tests seem to be failing with a release build

### ISSUE THREAD

**Issue by koverstreet** [rust-num/num#127]
Tests pass when testing the debug build (the default when running cargo test), but when I run cargo test --release, I get:

This is with latest git and rustc 1.4.0 (8ab8581f6 2015-10-27)

failures:
    integer::test_integer_i16::test_gcd_min_val_0
    integer::test_integer_i16::test_gcd_min_val_min_val
    integer::test_integer_i32::test_gcd_min_val_0
    integer::test_integer_i32::test_gcd_min_val_min_val
    integer::test_integer_i64::test_gcd_min_val_0
    integer::test_integer_i64::test_gcd_min_val_min_val
    integer::test_integer_i8::test_gcd_min_val_0
    integer::test_integer_i8::test_gcd_min_val_min_val
    integer::test_integer_isize::test_gcd_min_val_0
    integer::test_integer_isize::test_gcd_min_val_min_val
 
test result: FAILED. 198 passed; 10 failed; 1 ignored; 0 measured

**Comment by cuviper** [comment]
Interesting!  These are `#[should_fail]` tests where the gcd would be `MIN.abs()`, which can't be represented as a positive number.  In debug mode, you'll get "panicked at 'attempted to negate with overflow'", but release mode doesn't check overflows.  So it fails to fail. :)

The implementation is already checking for that min value explicitly to take special care, so I think we can just convert overflowing cases into explicit assertions, without too much overhead.

**Comment by cuviper** [comment]
I'm having second thoughts about changing the way `gcd()` panics, because then I'd potentially be introducing release-mode panics into other people's code.  Better to just tweak the test, I think...
