### ISSUE TITLE
Raw bit-preserving conversion from signed/unsigned to unsigned/signed

### ISSUE THREAD

**Issue by gnzlbg** [rust-num/num#141]
I'm implementing some bit manipulation algorithms on top of `PrimInt` and there are some situations in which I need to get an unsigned representation of the Integer type to operate on the bits directly using wrap around unsigned arithmetic. 

Is there a way to:
- obtain the unsigned integer type that has the same size as the current integer type
- cast the current type to its associated unsigned integer type preserving the bits (i.e. transmute)? 

The reciprocal operations (going from unsigned to signed) are also required.

**Comment by cuviper** [comment]
A simple cast like `value_i64 as u64` should do what you expect, preserving bits.  I'm curious though, what operations are you trying that require conversion?

There was [`IntSliceExt`](https://doc.rust-lang.org/1.0.0/collections/slice/trait.IntSliceExt.html), but this was never stabilized.

I could imagine adding `Signed` and `Unsigned` associated types to `PrimInt`, along with `as_signed` and `as_unsigned` methods.  (That's sort of a breaking change to extend a trait, but `PrimInt` isn't really expected to have external impls.)

**Comment by gnzlbg** [comment]
Maybe I expressed myself wrong. The use case I have is when writing a generic function that takes a `PrimInt` and I want to obtain a `Signed/Unsigned` int from it with the same size. When dealing with concrete primitive integers as you mention this is trivial.

**Comment by cuviper** [comment]
I'm asking for the motivation.  *Why* does that generic function want to convert signedness?  Do you have an example where this is clearly necessary and correct?

**Comment by gnzlbg** [comment]
Yes, a generic bit reverse algorithm in my PR uses them to simplify some
things.

**Comment by gnzlbg** [comment]
Basically if you implement some of these algorithms in an impl with concrete types then yes, you don't need these. 

Otherwise (implementing them in a free generic function or in the PrimInt trait) then you need something more than what the current `PrimInt` provides. 

The generic function might want to convert signedness because, e.g., an algorithm might be easy/fast for unsigned integers due to wrap around arithmetic but hard for signed integers. Converting whatever `PrimInt` you have to unsigned, and then back to the original type in a lossless way is easy. 

The opposite is also true, an algorithm might be fast for signed integers due to arithmetic shift (instead of logical shift).

In both cases, the algorithm works for all integers independently of their type/size as long as the proper bit representation can be used.

**Comment by cuviper** [comment]
Note that Rust is not like C/C++, where unsigned overflow is allowed and wraps, but signed overflow is undefined behavior.  In Rust, overflow is always considered a program error, although this is usually only checked in debug builds.  When left unchecked, Rust wraps normally for both signed and unsigned integers.  See [RFC560](https://github.com/rust-lang/rfcs/blob/master/text/0560-integer-overflow.md).

The point about arithmetic shifting is indeed useful, if you're taking advantage of sign extension in a signed type, or you want to avoid sign extension by using an unsigned type.

In general I'd advise against casting signedness unless you're absolutely sure it's necessary.  But these conversions are trivial to add, and should be no maintenance burden, so... OK.

Just for comparison, C++11 `<type_traits>` has [`make_signed`](http://en.cppreference.com/w/cpp/types/make_signed) and [`make_unsigned`](http://en.cppreference.com/w/cpp/types/make_unsigned).

**Comment by hauleth** [comment]
@cuviper actually Rust (unlike C++ but like C) define what program should do on over-/underflow. It is also considered "safe", debug asserts are only helpful warning for development purpose.

But I am also against this PR as I see no point in that. Is there any real world problem where such behaviour would be desirable?

**Comment by gnzlbg** [comment]
> @cuviper actually Rust (unlike C++ but like C)

C++ defines it as wrap around for unsigned integers and undefined behavior for signed integers. What does C define? (I thought C++ just deferred here to the C standard). 

> But I am also against this PR as I see no point in that. Is there any real world problem where such behaviour [sic] would be desirable?

The two most basic bit manipulation algorithms are logical and arithmetic shift. To perform a logical shift one needs an unsigned representation of an integer. To perform an arithmetic shift one needs a signed representation of an integer.  Any other non trivial algorithm (e.g. convert an unsigned to signed, and clamp to max/zero/whatever if the unsigned value is too large) needs a way to know for a given type, the signed/unsigned types of the same size.

From the point of view of an user that tried to extend `PrimInt` non-intrusively but that failed miserably, I had two options:

- I could either write a new trait, and implement an algorithm 8 times (e.g. using a macro), and then constrain my functions on `PrimInt` + my new trait (`PrimIntPlus`). 

- Or I could write the algorithm in a generic function constrained on `PrimInt` + another new trait `PrimIntAssociatedTypes`. Either way, I needed a new trait and maybe a macro. 

I found that nuts, and decided to modify `PrimInt` instead. Ideally, users willing to extend `PrimInt` with their own algorithms should just need to write them in a generic function constrained on `PrimInt`. I see anything else as a failure of `PrimInt`.

I also think that this is a prerequisite if we want to move some algorithms from the current `PrimInt` implementation from the macro to the trait. We don't need to do this, and arguably that can be considered masochism. Still, I think that we should at least strive to do so and try to see if the language or the rustc implementation could be improved to allow us to do so. If one cannot abstract over primitive integers easily from within a trait, how are users supposed to use Rust traits to abstract over more complicated things?  I don't think we will ever get rid of the implementation macro, but those associated types are a small step in that direction.

**Comment by cuviper** [comment]
C and C++ are the same with unsigned overflow wrapping but undefined behavior for signed overflow.  Rust's overflow is defined and safe for both, but still considered an error -- RFC560 is clear that implementations must check this when `debug_assert!` is enabled, and still may at other times.

Anyway, this just means overflow doesn't matter here, but arithmetic/logical `shr` still has a meaningful difference.  Maybe we should just add explicit `arithmetic_shr` and `logical_shr` functions, preserving signedness in the interface but doing whatever conversion is needed in implementation.  Those would fit conceptually well next to the existing `rotate_left` and `rotate_right`.  @hauleth?

I'm not too worried that `PrimInt` is itself macro-implemented, but its very purpose to let others write generic code on primitives, I agree.  Since @hauleth and I seem to agree that general signedness-conversion is dubious, let's identify what particular gaps we should fill, like `shr` above.

**Comment by hauleth** [comment]
:+1: for `arithmetic_shr` and `logical_shr` and shift left equivalents. This would be even better option than `<<` as it represents the idea of the operator. So yes, big **+** from me for that!

**Comment by gnzlbg** [comment]
I would love to have shar and shal next to shll and shlr. The operators <<
and >> are just too confusing in generic code when one doesn't know if the
type is signed or unsigned.

I think adding these is independent of whether the associated types
Signed/Unsigned make sense.

But it is worth discussing in detail how to add them since Shll/Shlr are
independent traits, so it could make sense to implement Shar/Shal in
separate traits as well, I am not sure.

Maybe we should open a different issue to discuss this more precisely?

**Comment by cuviper** [comment]
@hauleth, you want left equivalents just for completeness?  AFAIK those are identical.

@gnzlbg I'm not sure these need new shifting traits.  The sign-extending distinction only makes sense for fixed-width integers.  And if you still want to make the case for Signed/Unsigned associated types, please give an example of code that needs it.  The code you wrote in #142 `reverse_bit_groups` would be just fine signed if you had `logical_shr`, I think.  What other operation would require a particular signedness?

**Comment by cuviper** [comment]
It seems you've met your own need in your bitwise crate.
https://github.com/gnzlbg/bitwise
