### ISSUE TITLE
Wrapping neg is not implemented for PrimInt

### ISSUE THREAD

**Issue by gnzlbg** [rust-num/num#146]
When constraining on `PrimInt` there is no way of performing wrapping neg in a generic way.

The "generic" way to do this seems to be to call the `.wrapping_neg()` method which is offered by all primitive integers (but not by `PrimInt`).

**Comment by cuviper** [comment]
Hmm, it's odd that `std::num::Wrapping` doesn't implement `Neg`.

AFAICS `.wrapping_neg()` was only added in Rust 1.1, but we're still trying to maintain 1.0 compatibility.  Bumping that minimum version is a breaking change IMO.

I suppose you could do manual 2's complement, `x.not().wrapping_add(1)`.

**Comment by gnzlbg** [comment]
https://github.com/rust-lang/rust/issues/30524 was just oppened, looks like an overlook.

**Comment by gnzlbg** [comment]
> I suppose you could do manual 2's complement, x.not().wrapping_add(1).

Yes I could, thanks for the tip. 

> AFAICS .wrapping_neg() was only added in Rust 1.1, but we're still trying to maintain 1.0 compatibility. Bumping that minimum version is a breaking change IMO.

Could we use a `cfg` macro for that? E.g. if rust version >= 1.1 offer `wrapping_neg` in PrimInt, otherwise, not offer it?

**Comment by cuviper** [comment]
There's no cfg for the rust version, unfortunately.

**Comment by briansmith** [comment]
In the interim, you could add a new, off-by-default feature for `wrapping_neg`. Then people who need it could opt in to it, knowing that it requires Rust 1.1 or later.

**Comment by cuviper** [comment]
That's possible, if there's strong demand.  I don't want a combinatorial explosion of features though...

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-traits#10
