### ISSUE TITLE
Hide bigint implementation details

### ISSUE THREAD

**Issue by cuviper** [rust-num/num#155]
With `BigDigit` exposed in the interface, we're somewhat limited in what kind of changes we can make to the implementation.  Even just `fn new(digits: Vec<BigDigit>)` strongly implies that this storage will be directly used by the new `BigUint`.

**Comment by briansmith** [comment]
> Even just fn new(digits: Vec<BigDigit>) strongly implies that this storage will be directly used by the new BigUint.

I think that might be implied, but I don't think it is big deal if that isn't the case. You could leave `BigDigit` defined as it is currently and then use another name, e.g. `Limb` for the internal type. Then the public functions that take `BigDigit` values would just be `[deprecated]` conversion functions.

Note that `Limb` is a better name anyway, IMO. See this for the origin of the term `Limb`: https://gmplib.org/manual/Nomenclature-and-Types.html

**Comment by cuviper** [comment]
Yeah, that's true.  I think we even discussed on another issue that we could use careful transmutes and byte swaps to still reuse that storage, even when `Limb` is a different size.  So yes, we could change the implementation without actually affecting the API, then the only breaking change is to eventually remove the vestigial parts.

**Comment by cuviper** [comment]
`pub enum ParseBigIntError` is another pain point.  The way it tries to extend `ParseIntError` makes it clumsy to actually create errors, and we can't change this without breaking.  `ParseRatioError` is a better example how it should be, where the enum is hidden as a private field in a struct.

**Comment by cuviper** [comment]
It occurred to me recently that serialization is actually a breaking change too, because changes to type internals may alter the serialized format.  That's especially true when they're derived, like we're doing for `rustc_serialize`, but we should be careful even with our manual `serde` implementation.

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-bigint#3
