### ISSUE TITLE
Zero's documentation is out of date

### ISSUE THREAD

**Issue by durka** [rust-num/num#156]
It says Zero can be automatically derived using `#[deriving]` which is out of date syntax. And probably misleading anyway, since you'll need a compiler plugin to use such a derive.

**Comment by steveklabnik** [comment]
Given that the documentation doesn't seem to be uploaded on push, I also wonder if any other docs are out of date based on code.

**Comment by durka** [comment]
I checked the code, the Zero docs are there.

**Comment by cuviper** [comment]
Yeah, that's out of date.  Care to send a PR?

If someone wants to write a real `#[derive(Zero)]`, it would probably belong in `num-macros`, which currently just derives `FromPrimitive` for simple enums.  Nightly only, of course.

Docs are updated by `.travis/deploy.sh`.

**Comment by durka** [comment]
Oh, so there is not actually a `#[derive(Zero)]` at all anymore? I'll just delete the comment then.
