### ISSUE TITLE
impl Debug for ParseFloatError

### ISSUE THREAD

**Issue by durka** [rust-num/num#165]
Currently the result of `Num::from_str_radix` can't be unwrapped because `ParseFloatError` doesn't implement `Debug`. The workaround is to match or call `.ok()` but that's annoying.

Comments in the code indicate that all this is temporary until libstd's float from_str_radix stabilizes, but instead it was deprecated and removed, so num's implementation is seeming less temporary.

**Comment by cuviper** [comment]
Hmm, `from_str_radix` didn't stabilize, but `ParseFloatError` is stable even in 1.0.  But its fields are private, so we can't reuse it directly.  Adding `Debug` on ours sounds fine.
