### ISSUE TITLE
More isolated traits (Sqrt, Pow, ...)

### ISSUE THREAD

**Issue by azerupi** [rust-num/num#172]
When you try to make a generic function you want to be as generic as possible, but when your algorithm requires an operation like the square root or a power there is no isolated trait for that. 

If you use the std you have to make a wrapper trait around `sqrt` to use it as a trait bound. But I don't think it is a good idea that every crate makes their own wrapper for generic trait bounds.

If you use `num` you could use the Float trait, but then you add a lot of unnecessary constraints. 

Would it make sense to create a bunch of very generic and isolated traits that can be used as building blocks for more complex traits?

```rust
pub trait Sqrt {
    type Output;
    fn sqrt(self) -> Self::Output;
}
```

This trait can be implemented for `i32, i64, u32, u64, ...` with  `Output = f32 or f64`. It could be implemented for complex numbers, bigints, etc.

By having very specific traits you can have fine grained control on the trait bounds you want to impose and having them in the `num` crate will probably make them more universal across crates.

I'm interested in others opinions and experience about this

**Comment by hauleth** [comment]
I don't see the point. Is there a type that can be exponentiated but cannot be rooted? Also there is no cost in using `Num` only for `Num::pow` or `Num::sqrt`. It could be grouped into smaller traits but honestly I see no gain.

**Comment by azerupi** [comment]
That's not the point, if it makes sense to group power and root in one trait that is totally fine. The point of this request is to make more general and isolated traits so that generic functions can use more fine grained trait bounds. You may need mathematical operations that are not covered by `+`, `-`, `*`, `/`, `%` like `sqrt` or `pow` but don't want or can't implement the whole `num::traits::Float` trait.

Is there a drawback in making more smaller traits? I see only a gain, because you can use them stand-alone or compose more complex traits depending on them.

**Comment by cuviper** [comment]
Maybe it would help if your motivation was less generic? :)

Can you give a concrete example of a useful function generic on Sqrt, along
with a type that makes sense there but can't be Float?

It may be just that Float could be broken out a bit, but I cringe at having
one trait per function.  If nothing else, dealing with generic Output makes
it hard to do much else with that value.

**Comment by azerupi** [comment]
@cuviper First of all, I want to clarify that I am very inexperienced in generic programming. I may be doing it completely wrong, in which case I would gladly adopt a better solution.

>Maybe it would help if your motivation was less generic? :)

The reason why I think I need this is because I am learning DSP and I wanted to implement generic statistic methods: mean, variance, standard deviation. So I defined this trait:

```
pub trait Statistics<Output> {
    fn mean(&self) -> Output;
    fn variance(&self) -> Output;
    fn standard_deviation(&self) -> Output;
}
```

The mean and variance can be calculated with only `+`, `-`, `*` and `/` operations, but the standard deviation is defined as the square root of the variance.

I want to implement it for a struct `Signal<T>`. I don't really know what type `T` can be yet so I want to make it as generic as possible. If I use a trait bound that is more restrictive that just the operations than I need it feels like I am sacrificing a part of the genericity.

>If nothing else, dealing with generic Output makes it hard to do much else with that value.

I don't understand what you mean, could you explain this?

**Comment by cuviper** [comment]
The way you've written it, `variance` and `standard_deviation` have the same `Output` return type.  So to generically represent that, you'd have to restrict what kinds of `Sqrt` you're prepared to accept, something like `Statistics<Output> where Output: Sqrt<Output=Output>`.

Consider a different example, very simple, where you want to add square roots.  If you constrain the Output, it's not *too* bad, something like:

```rust
fn sum_sqrt<T>(a: T, b: T) -> T
    where T: Sqrt<Output=T> + Add<Output=T>
{
    a.sqrt() + b.sqrt()
}
```

But trying to allow more genericity:

```rust
fn sum_sqrt<T>(a: T, b: T) -> <<T as Sqrt>::Output as Add>::Output
    where T: Sqrt, <T as Sqrt>::Output: Add
{
    a.sqrt() + b.sqrt()
}
```

I *think* that's right.  It would have been even more "fun" if I tried to allow two different parameter types, and good luck if the expression is any more complex than that.

So that's why I think generic `Output` is annoying.  Notice all of `num::traits` tie every `Output=Self` (and implicitly leave RHS=Self), which makes them actually ok to work with.

**Comment by cuviper** [comment]
Historically, `num` was basically the dumping ground when the standard library folks said, "OMG, all these traits are ridiculous, out!"  They didn't want to stabilize any of it, but people do want some of this functionality, so here we are maintaining the `num` crate.

I think we should try to be a little cautious about expanding our scope further.  I don't mean to mimic the long process of the standard library, going through rfc and stabilization.  But let's try to make sure things will really be useful before we dump more into `num`.

Maybe you could just try out your ideas of `Sqrt` etc. on your own first?  Implement these traits in your own libraries where you want to use them, and see how it works out.  When you have some experience with it, if it indeed proves useful, you'll have a nice example to show us as motivation.  You'll probably even be just a short step away from turning it into a pull request!

**Comment by azerupi** [comment]
>Maybe you could just try out your ideas of Sqrt etc. on your own first? Implement these traits in your own libraries where you want to use them, and see how it works out. When you have some experience with it, if it indeed proves useful, you'll have a nice example to show us as motivation.

Ok, this seems totally reasonable. Thanks for your time :)

**Comment by cuviper** [comment]
> Another thing I thought about: In the std integers don't implement the square root method. Wouldn't it make more sense for them to implement it but returning a floating point value?

Maybe you want integer square root to return `f64`; maybe someone else wants `f32`; maybe a third person wants the [periodic continued fraction](https://en.wikipedia.org/wiki/Square_root#As_periodic_continued_fractions) to represent it exactly. :)

I think the standard library would just suggest you cast it yourself, `(i as f64).sqrt()`, if that's the resulting type you want.

**Comment by azerupi** [comment]
>Maybe you want integer square root to return f64; maybe someone else wants f32; maybe a third person wants the periodic continued fraction to represent it exactly. :)

Yes, but isn't that exactly the purpose of generic outputs? I'm a bit lost I must say. 

For example, the traits [`std::convert::From`](https://doc.rust-lang.org/std/convert/trait.From.html) and [`std::convert::Into`](https://doc.rust-lang.org/std/convert/trait.Into.html) can be implemented for multiple combinations of origin and target types. Why is this not desirable in the case of the square root?

**Comment by cuviper** [comment]
Well, if you want multiple possible outputs, it has to be another trait parameter, not an associated type like you first wrote.  Whether that's desirable? Try it and see...

**Comment by azerupi** [comment]
>Well, if you want multiple possible outputs, it has to be another trait parameter, not an associated type like you first wrote.

Ok, thanks for the clarification :)

>Whether that's desirable? Try it and see...

I will, but I would also be interested in the opinions of people who are more experienced than I in generic programming ;)
