### ISSUE TITLE
Add trait that allows using `as` operator for generic code

### ISSUE THREAD

**Issue by bluss** [rust-num/num#183]
The `as` operator does unchecked conversion between numerical types, without error cases. It's a core part of the language, so it would be useful to have it available for generic code as well.

Often it can be used very sensibly because you know your input is well behaved. For example, it can be small magnitude floating point numbers that you want to cast to/from f32/f64.

**Comment by Binero** [comment]
It also appears impossible to cast from `f64` to `num::traits::Float`. 32 bit idem.

**Comment by bluss** [comment]
Yes, `Float` is not a "trait object compatible" trait (a.k.a. "object safe"), so it can not be used as a type like that. I don't think that's expected, not every trait is made to be object compatible.

**Comment by Binero** [comment]
It does make code generic over Float very hard to write, as it's not possible to use constants. In my specific instance, I had to multiply the `Float` input by Euler's number, which was impossible. I cannot make a `Float` from an `f64`.

**Comment by bluss** [comment]
Euler's number is accessible from `Float` though, `F::exp(F::one()) where F: Float`. Not so nice maybe..

**Comment by bluss** [comment]
I'm using [asprim](https://crates.io/crates/asprim) in the mean time, but it is much better for crate interoperation if this kind of feature is already included in the float trait.

**Comment by hauleth** [comment]
You can always use `FromPrimitive` or `From`.

**Comment by Enet4** [comment]
Just bumping this issue, as I believe that this crate could benefit from an `AsPrim` trait. I have a use case where an N-dimensional volume of primitive elements are linearly transformed and converted to a compile-time value type `T` on reading. The other traits don't work because I would prefer precision loss over not obtaining a value at all. The `asprim` crate is nice, but this being covered by `num` is almost a normal expectation, and would more easily implement the trait for other numeric types such as `Complex`.

**Comment by cuviper** [comment]
> more easily implement the trait for other numeric types such as Complex.

It's an infallible conversion -- would you just silently drop the imaginary part?  I think it's better to make that explicit, like `value.re.as_()`.

**Comment by Enet4** [comment]
> It's an infallible conversion -- would you just silently drop the imaginary part? I think it's better to make that explicit, like `value.re.as_()`.

That is true, this conversion might bring some confusion. The main problem is that I'm dealing with the boundaries between a data type only known at run time and a compile-time type decided by the API user. Perhaps I need to rethink my approach, but I couldn't make such a conversion explicit (at least not without specialization or something similar).

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-traits#7
