### ISSUE TITLE
Implement to_bigint for &str, String types

### ISSUE THREAD

**Issue by andylamp** [rust-num/num#184]
I have a case where I have to parse and convert to BigInteger numbers that are provided as strings (e.g. streaming, text files etc). I found this functionality to be missing, since it's not that difficult to implement would it be a desirable one?

**Comment by cuviper** [comment]
You can use `from_str` or `from_str_radix` for this, or `str::parse` which uses `from_str`.

**Comment by andylamp** [comment]
@cuviper I noticed that already, but I just said that for consistency as this is implemented for all primitive types I thought we should have one for these types as well -- which as you said, would be mainly a wrapper around `from_str`. This would enable me to write `"1234".to_bigint()`.

**Comment by cuviper** [comment]
IMO, `to_bigint` is just for numeric conversions, and string parsing is quite different.
