### ISSUE TITLE
Failing assertion while multiplying two BigUints

### ISSUE THREAD

**Issue by Armavica** [rust-num/num#187]
```
extern crate num;
use num::CheckedMul;
use num::bigint::BigUint;
 
fn main() {
    let s = "531137992816767098689588206552468627329593117727031923199444138200403559860852242739162502232636710047537552105951370000796528760829212940754539968588340162273730474622005920097370111";
    let a: BigUint = s.parse().unwrap();
    let b = a.clone();
    let _ = a.checked_mul(&b);
}
```
The code above crashes at [this assertion in num-bigint](https://github.com/rust-num/num/blob/master/bigint/src/lib.rs#L783):
```
thread '<main>' panicked at 'assertion failed: carry == 0', /home/virgile/.cargo/registry/src/github.com-88ac128001ac3a9a/num-bigint-0.1.32/src/lib.rs:783
```
while it runs fine with one digit less in `s`. The same problem occurs with an unchecked multiplication.

I am not sure how to interpret the comment below the assertion; is there an allocation I should make manually?

**Comment by cuviper** [comment]
This is definitely a bug in the implementation, not something you did or should have done.  The comments around that assertion are just development details from #133.  In fact, @koverstreet if you see this, I'd appreciate if you can take a look.

FWIW, `CheckedMul` will always succeed on `BigUint` (barring bugs like this), so you can just use plain multiplication unless you need to be generic for other types too.

**Comment by koverstreet** [comment]
I'll dig into it first thing tomorrow.
