### ISSUE TITLE
`Integer` does not implement `Copy` trait

### ISSUE THREAD

**Issue by andylamp** [rust-num/num#191]
Unless I am mistaken here, `Integer` doesn't implement the `Copy` trait; thus I can't do stuff like

```rust
let v = 120.to_bigint().unwrap();
let b = v + v;
```
This is a real pain as if you want to just use a pre-computed result afterwards (e,g, if you want calculate a summation then multiply the result) this "inconvenience" makes it that much harder (and inefficient as well). Am I missing something here?

**Comment by cuviper** [comment]
As a rule of thumb, only primitives and aggregates composed of just primitives can implement `Copy`.  So for instance, `PrimInt` does implement `Copy`, but `BigInt` has a `Vec` underneath, so it can only be explicitly cloned.

For your tiny example, you could add by reference: `let b = &v + &v;`

Also consider `let v: BigInt = 120.into()`, or `let v = BigInt::from(120)`, so you don't have to unwrap.

**Comment by Emilgardis** [comment]
Is there any implementation of a `BigUint`-like struct/type that does implement copy?

**Comment by andylamp** [comment]
@cuviper well, I would've understood that but the docs are scarce on details as well as examples on many parts -- thanks for letting me know. Also thanks for the tips!

PS As @Emilgardis are there any BigInt types that do implement it?

**Comment by cuviper** [comment]
Any arbitrarily-sized integer type is going to have to manage a memory buffer somehow, which will preclude simple copying.  Perhaps one could implement a copy-on-write sharing strategy, so at least clones are cheap, but that still couldn't implement `Copy `.

**Comment by andylamp** [comment]
@cuviper thanks for your insight; on a side note do you mind if I add more examples to the docs? As I've found myself struggling with little things like this and docs didn't not provide examples for most cases.

**Comment by cuviper** [comment]
Sure, I would welcome improvements to the documentation!

**Comment by Emilgardis** [comment]
One thing that could be added is a macro that makes a type that behaves like a BigUint, but instead of a vec, it is an array with a specified size. Ofc then it could also include Sign, so that it could work as a BigInt

**Comment by cuviper** [comment]
Yes, you could use a fixed array for a large bounded integer type, and this
could implement `Copy `.  Of course, if you choose a large array you may
start to notice that copies are not totally free for performance.

**Comment by cuviper** [comment]
Closing -- hopefully it's clear now why we can't require `Copy`.
