### ISSUE TITLE
`Ratio` methods poorly documented

### ISSUE THREAD

**Issue by ExpHP** [rust-num/num#208]
This is a couple of related but minor issues in one; I can break it up if need be.

**Ratio::to_integer**

There are at least four possible choices of semantics I can think of for a method with the name and signature `to_integer(&Ratio<T>) -> T`:

* Panics if non-integral
* Equivalent to `x.floor().numer().clone()`
* Equivalent to `x.round().numer().clone()`
* Equivalent to `x.trunc().numer().clone()`

The fourth bullet is the correct answer, but the documentation does not clarify this.

(though tbh I rather wish it were `-> Option<T>` instead...)

**Ratio::fract**

Similar issue; is this equivalent to `x - x.floor()` or `x - x.trunc()`?  I cannot tell from the docs.

**Ratio::reduced**

The very fact that this method is public makes me concerned, because **I cannot tell when it needs to be used!**  ~~Aside from `new_raw`, are any methods of `Ratio` capable of producing a non-reduced fraction?~~ Without using `new_raw`, is there any way to obtain a non-reduced fraction? If so, I would hope to see them collected in a place where one could easily find them; perhaps in the doc for either the struct or `reduced`.

(and if not, honest question: why is `reduced` public?)

---
(edited because while obviously e.g. `new_raw(x,y).recip()` or `new_raw(x,y).pow(3)` might produce non-reduced fractions, I would sooner blame that on contract violation)

**Comment by cuviper** [comment]
I would welcome a PR improving documentation!

But I would try to avoid describing much in terms of other methods.  For instance, while it's true that `to_integer()` is just `self.trunc().numer`, it may not always be so.  I look at that now and think it should be implemented the other way, where `trunc()` is `from_integer(self.to_integer())`, so we don't have to create an intermediate ratio when just getting the integer part.  So, the documentation should describe the semantics (round toward zero), not the implementation.

On `reduced` -- yeah, I don't like that this is public either, nor `new_raw`.  Chalk it up to historical baggage.  Perhaps they should be `unsafe`, if they are kept public at all, but this will be a breaking change.

I'm not aware of other ways to get non-reduced values, although `recip` does fail to maintain `denom>0`.  It might not hurt to dig through and audit this stuff again...

**Comment by ExpHP** [comment]
> So, the documentation should describe the semantics (round toward zero), not the implementation.

I totally agree; my above definitions were just for the sake of brevity in this discussion.

> On reduced -- yeah, I don't like that this is public either, nor new_raw. Chalk it up to historical baggage. Perhaps they should be unsafe, if they are kept public at all, but this will be a breaking change.

Hm, I would be disappointed if `new_raw` disappeared!  Rationals are frequently useful in number theoretic problems, and I often find myself constructing rationals from values already proven to be coprime.  As a suggestion, perhaps `new_raw` could `debug_assert!` its invariants instead?

As I see it, the real danger would be something like `Ratio::{denom,numer}_mut()`; thankfully, that footgun isn't provided!

> I would welcome a PR improving documentation!

Sure, I will take a stab at this when I can.

**Comment by ExpHP** [comment]
> I'm not aware of other ways to get non-reduced values, although recip does fail to maintain denom>0. It might not hurt to dig through and audit this stuff again...

Going through it it looks like on the whole the implementation just can't make up its mind on whether negative denominators [are allowed](https://github.com/rust-num/num/blob/c22e3bf9a2733/rational/src/lib.rs#L262), or if they [are forbidden](https://github.com/rust-num/num/blob/c22e3bf9a2733/rational/src/lib.rs#L103)...  It's bothering me quite a bit and I'm tempted to start cleaning it up.

**Comment by cuviper** [comment]
Creating a zero denominator is the other part, where `recip` should probably just panic.

One *small* advantage of allowing negative denominators is that it can enable `i32::MIN`, for instance, which can't be represented as positive.  You could even cheat and represent a true `abs(i32::MIN)` with `Ratio(i32::MIN, -1)`.  But I'll bet a lot of the code will fail on this kind of corner case.

> It's bothering me quite a bit and I'm tempted to start cleaning it up.

Please do!
