### ISSUE TITLE
Implement to_radians and to_degrees for Float

### ISSUE THREAD

**Issue by frewsxcv** [rust-num/num#211]
https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.to_degrees

https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.to_radians

To better mirror what's offered in the standard library, it'd be nice if these methods were available for any `Float`.

**Comment by cuviper** [comment]
Curious that those are missing.  Is there anything else in `f32` and `f64` that we lack?

It's a breaking change to add methods to a trait, unless you provide a default implementation.  Is there a way to generically write these?  Then `f32` and `f64` can override with their native versions, of course.

**Comment by frewsxcv** [comment]
Relevant discussion in https://github.com/georust/rust-geo/pull/48 by the way. Feel free to take any of my code I wrote.

**Comment by cuviper** [comment]
Ugh.  Rust 1.0 had these stable for `f64`, but not until 1.7 for `f32` .  (rust-lang/rust#30672)

**Comment by frewsxcv** [comment]
What would be the next step forward for this? In what way would it be a breaking change? Do you think it'd be possible to write a default implementation?

**Comment by cuviper** [comment]
It's a little annoying since their `Float` implementations are shared, but I can code it openly for now.  And I think I've got a way to write a default too, so it's not a breaking change.

**Comment by cuviper** [comment]
Please let me know if #212 looks ok to you.
