### ISSUE TITLE
Add method `is_one` to `One` trait

### ISSUE THREAD

**Issue by pyfisch** [rust-num/num#214]
The [`Zero` trait](http://rust-num.github.io/num/num/trait.Zero.html) contains two methods: `zero` returns the number 0 for the given type and `is_zero` is provided and can be used to check if a number is 0.

The [`One` trait](http://rust-num.github.io/num/num/trait.One.html) is similar but contains only the method `one` to create the number 1. Please also add a method to check if a number is one.

**Comment by cuviper** [comment]
Sure, I'm fine with that. It should be easy if you'd like to add that
yourself and send a PR.

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-traits#5
