### ISSUE TITLE
Roundoff error when doing scalar division of Complex64

### ISSUE THREAD

**Issue by fkjogu** [rust-num/num#217]
Transforming all scalar operations to complex arithmetics leads to numerical roundoff errors when doing scalar division of a `Complex64`, compared to a direct floating point division.

Consider this minimal arbitrary example

``` rust
extern crate num;

use num::complex::Complex64;

fn main() {
    let r = 98.29372511785971;
    let c = Complex64::new(0., r);
    let s = 25.;
    assert_eq!(c / s, Complex64::new(0., r / s));
}
```

I'd expect it to be exactly the same, which is not the case. This is due to the much more complicated calculation dividing to `Complex64`.

This might be a philosophical issue, but I find it unnecessary to convert a scalar to a complex number first. Not only it introduces some additional error, but also adds to runtime.

In my opinion we should use specialized scalar arithmetic, which should be easily doable, thanks to macros.

Shall I turn this into an pull request?

**Comment by cuviper** [comment]
> I'd expect it to be exactly the same, which is not the case.

Even direct floating point division like `assert_eq!(a/b, a/b)` can't be assured in general.  Some architectures, especially x86, may store values in registers with more precision than they would have stored in memory.

But we can probably do better here, regardless.

> In my opinion we should use specialized scalar arithmetic, which should be easily doable, thanks to macros.

Right, they're already converted naively with the `real_arithmetic!` macro.  If you'd to implement each op more directly, that would be great.

> Shall I turn this into an pull request?

Sure!

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-complex#4
