### ISSUE TITLE
Add support for rounding rational numbers to the nearest f64 and f32

### ISSUE THREAD

**Issue by jrmuizel** [rust-num/num#221]
This would be nice to have.

**Comment by jrmuizel** [comment]
The python implementation of a similar thing is here:
https://hg.python.org/cpython/file/3f337cce758c/Objects/longobject.c#l3670

**Comment by hauleth** [comment]
I have created small utility library some time ago that would need to get some love now https://github.com/hauleth/inter that I believe does exactly that.

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-rational#4
