### ISSUE TITLE
Remove default `epsilon` implementation for `Float`

### ISSUE THREAD

**Issue by AtheMathmo** [rust-num/num#232]
With #231 we introduced a new `epsilon()` function which returns the `EPSILON` constant for `f32` and `f64`. In order to prevent breaking the API we provided a default implementation here - using `NumCast` to return `f32::EPSILON`.

When we are ready to release breaking changes we should consider removing this default implementation.

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-traits#4
