### ISSUE TITLE
Why does Complex.norm_sqr clone its parts?

### ISSUE THREAD

**Issue by marcosscriven** [rust-num/num#249]
I'm new to Rust, so this may be a dumb question. However, looking at the implementation of ```Complex.norm_sqr``` I was shocked it makes four clones:

```
    pub fn norm_sqr(&self) -> T {
        self.re.clone() * self.re.clone() + self.im.clone() * self.im.clone()
    }
```

I looked at the annotation for this line, and found this change by @gifnksm : https://github.com/rust-num/num/commit/a325a566c6a8a254377e072bddd5b347b6ace1df

It seems that this was the cost of working with reference type numbers? However, would this not mean that a loop that uses this a lot would create unnecessary copies, even for simple/copy types?

I found this by way of following a Rust tutorial which used the Mandelbrot set as an example:

```
fn escapes(c: Complex<f64>, limit: u32) -> Option<u32> {
    let mut z = Complex { re: 0.0, im: 0.0 };
    for i in 0..limit {
        z = z*z + c;
        if z.norm_sqr() > 4.0 {
            return Some(i);
        }
    }

    return None;
}
```

**Comment by marcosscriven** [comment]
I just tried a little benchmark:

```
extern crate num;
extern crate time;

use num::Complex;
use time::PreciseTime;

fn main() {
    let z = Complex { re: 0.26555, im: 0.0 };
    let times = 100_000_000;
    time(times, "norm_sq", &|| z.norm_sqr());
    time(times, "local_norm_sqr", &|| local_norm_sqr(z));
    time(times, "noclone_local_norm_sqr", &|| noclone_local_norm_sqr(z));
}

fn time<T>(times: i32, message: &str, f: &Fn() -> T) {
    let start = PreciseTime::now();
    for _ in 0..times {
        f();
    }
    let end = PreciseTime::now();
    println!("{} took {} seconds.", message, start.to(end));
}

fn local_norm_sqr(c: Complex<f64>) -> f64 {
    c.re.clone() * c.re.clone() + c.im.clone() * c.im.clone()
}

fn noclone_local_norm_sqr(c: Complex<f64>) -> f64 {
    c.re * c.re + c.im * c.im
}
```

On my machine, this results in:
```
norm_sq took PT5.646662627S seconds.
local_norm_sqr took PT4.009341609S seconds.
noclone_local_norm_sqr took PT2.902629376S seconds.
```

**Comment by marcosscriven** [comment]
Ping @jimblandy on the above, as it's his awesome book on Rust I'm working through, and the ```escapes``` function I pasted uses this.

**Comment by cuviper** [comment]
Once upon a time, Rust operators weren't as flexible as they are now.  These days, operators can be implemented by value, by reference, or both (e.g. val+val, ref+ref, val+ref, ref+val). But in order to use any of that in generic code, you have to have a trait bound.  `Complex` only requires `Clone + Num`, and `Num` only requires operators by value (see #94).  So for `Complex::norm_sqr`, we're stuck cloning.

But I'll bet you did not run your benchmark in `--release` mode, with optimizations.  With `Complex<f64>`, there should be no observable difference between a clone or a copy, except that in debug mode the `clone()` will make a real function call.  When optimized and inlined, `f64` clone/copy should be the same.

Actually, with optimization `rustc` discards your whole benchmark as unused results, "completing" them in nanoseconds -- basically just the overhead of the timing functions.  If you use a nightly compiler and the `#[bench]` infrastructure, `test::black_box` can prevent it from discarding those intermediate results.

**Comment by marcosscriven** [comment]
Thanks for the response. As a quick way to force keeping the intermediate results, I summed them:

```
extern crate num;
extern crate time;

use num::Complex;
use time::PreciseTime;

fn main() {
    let z = Complex { re: 1.0, im: 1.0 };
    let times = 100_000_000;
    time::<f64>(times, "norm_sq", &|| z.norm_sqr());
    time::<f64>(times, "local_norm_sqr", &|| local_norm_sqr(z));
    time::<f64>(times, "noclone_local_norm_sqr", &|| noclone_local_norm_sqr(z));
}

fn time<T>(times: i32, message: &str, f: &Fn() -> f64) {
    let start = PreciseTime::now();
    let mut sum = 0.0;
    for _ in 0..times {
        sum += f();
    }
    let end = PreciseTime::now();
    println!("{} took {} seconds. Sum:{}", message, start.to(end), sum);
}

fn local_norm_sqr(c: Complex<f64>) -> f64 {
    c.re.clone() * c.re.clone() + c.im.clone() * c.im.clone()
}

fn noclone_local_norm_sqr(c: Complex<f64>) -> f64 {
    c.re * c.re + c.im * c.im
}
```

This results in:

```
norm_sq took PT6.002303519S seconds. Sum:200000000
local_norm_sqr took PT4.231227566S seconds. Sum:200000000
noclone_local_norm_sqr took PT3.350320909S seconds. Sum:200000000
```

But you're correct of course, running in release mode yields much lower results, and, more to the point, consistent across the different methods:

```
norm_sq took PT0.092838745S seconds. Sum:200000000
local_norm_sqr took PT0.090795609S seconds. Sum:200000000
noclone_local_norm_sqr took PT0.090786698S seconds. Sum:200000000
```

This reduces the added cost of ```norm_sq``` to just a couple of percent.

**Comment by cuviper** [comment]
From run to run, I see the "winner" in your updated benchmark vary, sometimes being the non-local `norm_sqr`.  I think this is within variance, as there really should be *no* codegen difference when inlining is done.  FWIW, `#[bench]` is a bit more rigorous about running in repeated loops and reporting variance.

Feel free to ask if you have further questions...

**Comment by marcosscriven** [comment]
Thanks your responses @cuviper - I heard the Rust community was helpful, and this only adds to that impression.
A deep understanding of what the compiler does is clearly important in understanding how to write the broadest possible generic methods efficiently.
