### ISSUE TITLE
New release for num-macros?

### ISSUE THREAD

**Issue by antiagainst** [rust-num/num#253]
The previous release `0.1.36` was on Sep. 30, 2016. And later https://github.com/rust-num/num/commit/7ebef5bbe6b0109b72d2d7246f8b4ed205fdffba fixed a compilation problem. It would be nice to push a new release onto crates.io so this fix can be leveraged.

**Comment by hauleth** [comment]
`num-macros` are deprecated in favour of `num-derive`

**Comment by antiagainst** [comment]
@hauleth: Oh, cool! Using `num-derive` also solves the compiler warning of `#[derive] for custom traits is deprecated`. Good to know! Thanks! :)

**Comment by cuviper** [comment]
Well, I just published new `num-macros` and `num-derive` anyway. :)
