### ISSUE TITLE
Add `Wrapping[...]` traits (similar to `Checked` traits)

### ISSUE THREAD

**Issue by nwin** [rust-num/num#255]
I was about to file an issue that we need these traits because I couldn’t find them.

We should resemble the wording that is used in the stdlib which has a type named `Wrapping` and several `wrapping_[...]` methods.

Any thoughts about that?

**Comment by cuviper** [comment]
The standard library also has `checked_op` methods, which is what these `Checked` traits represent, and are very different from wrapping.

**Comment by nwin** [comment]
Oh, my bad. You’re right.
