### ISSUE TITLE
Implement more formatting traits

### ISSUE THREAD

**Issue by clarcharr** [rust-num/num#259]
It'd be nice if every struct implemented `LowerExp`, `UpperExp`, `Binary`, `Octal`, `LowerHex`, and `UpperHex`.

These would make it a lot nicer to print things like `BigInt` and `Ratio`, which currently only have `Debug` and `Display`.

**Comment by clarcharr** [comment]
See also: rust-lang/rust#39479.

**Comment by cuviper** [comment]
num-complex now has all of these.

num-bigint has all but `LowerExp` and `UpperExp`, which could actually be interesting for large numbers, especially if we can figure out how to do that *quickly*, without full digit-by-digit division.

num-rational still needs them all.

**Comment by cuviper** [comment]
Closing in favor of separate issues, rust-num/num-bigint#6 and rust-num/num-rational#1.
