### ISSUE TITLE
Use derive_more crate to derive basic arithmetic traits

### ISSUE THREAD

**Issue by JelteF** [rust-num/num#260]
I've created a library called [derive_more](https://github.com/JelteF/derive_more) that allows deriving of basic traits to decrease boilerplate code, such as `From`, `Add`, and `Mul`. With the recent release of Rust 1.15 it now works on stable rust. 
I think this would be a crate that would benefit from using it. For instance this code could be derived with the library: https://github.com/rust-num/num/blob/master/complex/src/lib.rs#L442-L462

I don't mind making a pull request for this, but wanted to ask first i it is even wanted.

**Comment by cuviper** [comment]
First of all, we treat raising the rustc requirement as a breaking change.  I know not everyone agrees with that policy, but I prefer the more conservative position.  We might raise the bar a little for #257, or go ahead and break a lot for #261, not sure yet.

I think `derive_more` looks nice in general, especially for folks writing newtypes and enum wrappers.  I'm just not sure we have enough use for it here to justify an extra dependency.  I think `Complex` might be the only case that could really use it, and that boilerplate is pretty simple, and already written anyway.

**Comment by cuviper** [comment]
I don't think we'll do this without stronger justification.
