### ISSUE TITLE
pow for bigint types is missing

### ISSUE THREAD

**Issue by Apromixately** [rust-num/num#264]
I cannot find a pow function for bigint types but I am new to rust so I might just not have the right includes.

**Comment by clarcharr** [comment]
There's a standalone pow function that should work for you.

**Comment by cuviper** [comment]
There is a generic [pow](http://rust-num.github.io/num/num_traits/pow/fn.pow.html) which should work fine for bigint types.
The docs show using it as `num_traits::pow`, but it's re-exported as `num::pow` too.

**Comment by clarcharr** [comment]
(Perhaps a more optimised version could be made for bigint which allocates extra memory in advance.)

**Comment by cuviper** [comment]
There's also #153 which speeds it up a lot multiplying by reference.  That's a breaking change to make to the generic interface, but we *could* add an inherent method on `BigUint` and `BigInt` optimized thus.

**Comment by clarcharr** [comment]
I mean, we do know exactly how much memory is necessary; just multiply the number of bits we currently need by the exponent.

**Comment by cuviper** [comment]
That's merely an upper-bound. e.g.
- 4 (3 bits) exp 7 = 16384 (15 bits)
- 7 (3 bits) exp 7 = 823543 (20 bits)

**Comment by cuviper** [comment]
It might still be close enough though.  Anyway, if you want to write a PR, I'd be happy to see it.

**Comment by clarcharr** [comment]
Nah, it's pretty exact. Take the largest bit and write it as 2^n. (2^n)^exp is just 2^(n*exp).

**Comment by cuviper** [comment]
That doesn't work in the example I showed.  The largest bit is 4 = 2^2.  (2^2)^7 = 2^14, 15 bits, but 7^7 is 20 bits.  In fact, I think using the MSB this way gives you a *lower* bound on bits.

**Comment by cuviper** [comment]
So if a number `N` has `B` bits, then `pow(N, exp)` will have `[(B-1)*exp, B*exp)` bits.

**Comment by clarcharr** [comment]
…you're right. I should know better.

2^n where n is the largest power of two that fits the bits, is an upper bound. 2^n where n is MSB is lower bound.

I think that right now if we start with the lower bound, then we're at a good start. I could probably provide a decent optimisation with just that.

**Comment by Apromixately** [comment]
I tried this:

extern crate num;

use num::bigint::BigInt;
use num::FromPrimitive;
use num::pow;

fn main() {
    let foo: BigInt = FromPrimitive::from_u8(2).expect("ffs");
    println!("well: {}", foo.pow(3));
}

but it does not work.

**Comment by cuviper** [comment]
It's not an inherent method, at least not yet -- that's what @clarcharr and I were discussing.
For now, use `pow(foo, 3)`.

**Comment by Apromixately** [comment]
Sorry, deleted my comment. But yes, that's what I needed!
