### ISSUE TITLE
Any plans for Fixed Point numbers?

### ISSUE THREAD

**Issue by fulara** [rust-num/num#265]
Are there any plans to support Fixed Point numbers?
I did a search on crates and did not find any implementation.
BigRational is too slow for me.
and I could not get Ratio<i64> working for my case. (overflow issues).

**Comment by cuviper** [comment]
See issue #8 and PR #224 for `BigDecimal`, although I think there are still some unanswered questions.

**Comment by fulara** [comment]
Yep, saw that. But thats regarding the BigDecimal - which would have infinite precision. 
I am looking form something having decimal representation but not being as slow as BigDecimal probably would be. 

Any plans for d64  or d128 in this library?

**Comment by hauleth** [comment]
In theory it shouldn't be that hard. However truly fixed point arithmetic isn't possible until we get Π types so you could write:

```rust
let a: Fixed64<10> = 10.into(); // 64 bit digit with 10 digits after decimal point
let b: Fixed64<5> = 10.into();

// a + b would be impossible as their type is different
```

Currently only solution would be using `typenum` crate which is quite slow when compiling. So I hope that in future it will be possible (as I would ❤️ to have Π types as I could make good use of them in my Octavo library).

**Comment by icefoxen** [comment]
It should be easy to write a macro that constructs a fixed-point number type to the given specifications, so:

```
// Create a signed 64-bit number with 10 bits after the decimal point
fixed_point!(Fix64_10, i64, 10);

let a: Fix64_10 = 10.into();
let b: Fix64_10 = 20.into();
a + b
```

**Comment by scottjmaddox** [comment]
There's a typenum-based implementation [here](https://github.com/japaric/fpa/blob/master/src/lib.rs), that looks interesting. It might be better to limit the library to defining the macro's, and let the library users instantiate the types of interest (as suggested by icefoxen), though. Otherwise compilation time could quickly explode with the number of types, especially if you tried to provide all possible converting functions (mul, cast, etc.).

**Comment by cuviper** [comment]
I don't have any plans to implement this in the rust-num organization, but maybe `fpa` or some other crate could work for you.
