### ISSUE TITLE
Dependence of num-complex on num-traits should be external

### ISSUE THREAD

**Issue by termoshtt** [rust-num/num#276]
## Problem
I have met an error message

```
the trait `num_traits::identities::Zero` is not implemented for `num_complex::Complex<f64>`
```

when I use latest num-complex to enable #275 and usual num-traits:

```
num-complex = { git = "http://github.com/rust-num/num" }
num-traits = "0.1"
```

## Detail
In my understanding, this is caused by the dependency definition in complex/Cargo.toml:

```
[dependencies.num-traits]
optional = false
path = "../traits"  # due to this line!
version = "0.1.32"
```

Due to this, `Complex64` in `num-complex = { git = "..." }` implements `Zero` of `num-traits = { git = "..." }`, which does not equal to `Zero` of `num-traits = "0.1"`. Actually, if I change my Cargo.toml

```
num-complex = { git = "http://github.com/rust-num/num" }
num-traits = { git = "http://github.com/rust-num/num" }
```

this error disappear on my crate. However, I cannot use my crate with another crate using `num-traits = "0.1"`, i.e. the most of numerical crate.

## Resolution
Revise dependency of num-complex on num-traits

```
[dependencies.num-traits]
optional = false
version = "0.1.37"
```

Indeed, my fork works well
https://github.com/termoshtt/num/tree/ext_dep

Thank you!

**Comment by cuviper** [comment]
Interesting!  We do want the path dependency for development purposes, and usually this is ignored when you get it from crates.io.  I'm surprised that Cargo doesn't resolve the git dependency similarly though.  This might be worth opening a Cargo issue too.  Maybe it will work better if you use `.cargo/config` instead for the git override?

But the short term answer is that I just need to publish a new num-complex for you...

**Comment by cuviper** [comment]
num-complex v0.1.37 is now published.  But we can leave this bug open until we find a better way to use num subcrates from git.

**Comment by termoshtt** [comment]
> num-complex v0.1.37 is now published. 

Thanks a lot, it is what I really need :smile:

**Comment by termoshtt** [comment]
> Maybe it will work better if you use .cargo/config instead for the git override?

`.cargo/config` technique is working for replacing `num-traits`!
But it seems not good to replace `num-compelx`. I prepare a model situation:

```
/tmp/
    alpha/
    num/   # cloned from git
    .cargo/config
```
```
%cargo tree
alpha v0.1.0 (file:///tmp/alpha)
├── num-complex v0.1.37 (http://github.com/rust-num/num#6513a561) # from git
│   ├── num-traits v0.1.37 (http://github.com/rust-num/num#6513a561) # from git due to "path"
│   └── rustc-serialize v0.3.23
└── num-traits v0.1.37    # from crate.io
```

and I put `.cargo/config` with

```
paths = ["num/traits"]
```

Then all two `num-traits` are replaced by `/tmp/num/traits` and works well :+1:

On the other hand, If I put 

```
paths = ["num/complex"]
```

cargo prints warning to use [replace] block

>%cargo build
warning: path override for crate `num-complex` has altered the original list of
dependencies; the dependency on `num-traits` was either added or
modified to not match the previously resolved version
This is currently allowed but is known to produce buggy behavior with spurious
recompiles and changes to the crate graph. Path overrides unfortunately were
never intended to support this feature, so for now this message is just a
warning. In the future, however, this message will become a hard error.
To change the dependency graph via an override it's recommended to use the
`[replace]` feature of Cargo instead of the path override feature. This is
documented online at the url below for more information.
http://doc.crates.io/specifying-dependencies.html#overriding-dependencies

This is warning, and the compile succeeds.

I think it is a better way to replace `num-traits` using `.cargo/config` as you suggest.

**Comment by cuviper** [comment]
I believe cargo [`[replace]`](http://doc.crates.io/manifest.html#the-replace-section) is the recommended way to do this now.
