### ISSUE TITLE
Fraction / extended float implementation

### ISSUE THREAD

**Issue by dnsl48** [rust-num/num#277]
Hey guys, I'm wondering if you would be interested in taking upstream the [fraction](https://github.com/dnsl48/fraction/) crate. It's extended float implementation based on rationals from `num` crate. I see you already working on `BigDecimal` implementation (no simple `Decimal` though). However, it does not imply having `NaN` and `Inf` values (neither do `Ratio`). The idea behind Fraction though is to be lossless and hashable float implementation.

**Comment by dnsl48** [comment]
perhaps it might even be reimplemented on BigDecimal what it's stable enough

**Comment by cuviper** [comment]
Honestly, no, I don't think we'll take on any additional crates at this time.  The folks interested in `BigDecimal` recently moved to an [external project](https://github.com/akubera/bigdecimal-rs), published as the [bigdecimal](https://crates.io/crates/bigdecimal) crate, and I think we'll keep it separate for now.  I'd be happy to add cross-reference links to the readme and/or `num` docs though!

**Comment by dnsl48** [comment]
Fair enough :) It also appears quite often that that having functionality in external crates helps to decouple dependencies within the code. Thank you for the quick response.
