### ISSUE TITLE
Any interest in arbitrary saturating numbers?

### ISSUE THREAD

**Issue by icefoxen** [rust-num/num#284]
I wrote up some code for creating numbers that are bounded to given limits, like so:

```
// Create a number that will never exceed 15
let x = BoundedUint(0, 15);
let y = x + 20;
assert_eq!(x, 15);
```

It's not particularly clever or efficient code, but it's nice to be able to enforce those sorts of checks transparently when you need them and someone else might want to do the same thing someday.  So if it's useful I'd like to contribute it to somewhere it'll be available, instead of just making yet another tiny random crate.

**Comment by cuviper** [comment]
I think a brand new type would be better served in its own crate, rather than immediately getting slowed down to the maintenance pace of `num`.

**Comment by icefoxen** [comment]
All right, thanks.
