### ISSUE TITLE
Implement FromStr for Complex

### ISSUE THREAD

**Issue by c410-f3r** [rust-num/num#289]
Would be nice to implement `FromStr` for `Complex`, is something blocking this feature?

```
let s = "3.0850107479750e-04 -4.9785737087053e-05";
let x = Complex::from_str(s).unwrap();
```

I could do some research and create a PR if you guys don't mind.

**Comment by cuviper** [comment]
Off hand, I don't know a good reason why not!  There are probably a lot of design questions for how flexible to be, like accepting *i*/*j* on the imaginary part, or letting the real and/or imaginary parts be optional, etc. But I can't think of anything actually blocking it.

**Comment by clarcharr** [comment]
I would personally prefer parsing from the formats `a+bi` or `a+bj`, allowing for spaces between the plus.

**Comment by c410-f3r** [comment]
[Matrix Market format](http://math.nist.gov/MatrixMarket/formats.html#MMformat) and [Harwell Boeing format](http://people.sc.fsu.edu/~jburkardt/data/hb/hb.html) are ASCII files that use the simplest complex number representation that I just mentioned above.
We could use this representation to implement `Num` and `FromStr` would delegate to `from_str_radix` the same way BigUint does.

**Comment by aliddell** [comment]
I'd be happy to help here. My own preference would be `a+/- bi` or `a +/- bj` but not both; `a`; or `b{i,j}`. It looks like when printed they end in `i`, so for consistency I would vote for that.

**Comment by clarcharr** [comment]
Seems good for me!

**Comment by cuviper** [comment]
Completed in #317.
