### ISSUE TITLE
Add keywords to crate

### ISSUE THREAD

**Issue by kw217** [rust-num/num#306]
I searched for a bignum crate on crates.io by typing "bignum" into the search bar. Several crates came up, but `num` was not one of them. I only found it by following a reference made to it in another crate.

Please can you add keywords to the crates.io entry, so `num` can be found when searching?

**Comment by cuviper** [comment]
We do have keywords for "mathematics" and "numerics", but yeah we should probably add more, and add some appropriate crates.io categories too.
