### ISSUE TITLE
Increment and decrement methods for Integer trait?

### ISSUE THREAD

**Issue by L117** [rust-num/num#307]
When dealing with primitive integers it's fast and easy to increment/decrement with `x += 1;`/`x -= 1;`, but with `BigInt`/`BigUint` it wastes an allocation and/or becomes tedious (Imagine calling `One::one`, `From::from` and defining `static ONE`). So such methods could come in handy.

**Comment by cuviper** [comment]
Sure, that could be useful.

The trait will have to provide default implementations in order for this to not be a breaking change, which means it probably has to require `Clone`.  e.g. `*self = self.clone() + Self::one()`.  But that's harmless for primitives and can be overridden in types like the bigints.

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-integer#2
