### ISSUE TITLE
Implement FixedInteger: Generalized fixed bit-width integer arithmetics.

### ISSUE THREAD

**Issue by Robbepop** [rust-num/num#308]
Implement efficient general fixed bit-width arithmetic in num.

For my current project I am in need of a library that can efficiently handle integer that have arbitrary but fixed bit-widths and thus operate similar to native rust integers (`u8`, `i8`, ..., `u64`, etc.).

For my own personal requirements they have to be as efficient as possibly implementable in today's rust. E.g. for certain bit-width (like native 8, 16, 32, 64 and 128) they should fall-back to their native operations for efficiency.

Questions about their interface have yet to be decided:

- Should they only be inter-operable with same-bit-width integers?
- How do they handle signed vs unsignedness? (For my personal use-case it would be best if they support both signed- and unsigned operations at the same time.)

An example simple and naive data structure for them could look similar to this:

```rust
struct FixedInt {
	/// The bit-width, used to dispatch between the variants of `FixedIntData`.
	bits: usize,
	/// The actual data to represent the value.
	data: FixedIntData
}

union FixedIntData {
	/// Space optimized (on stack) variant
	inl: Block,
	/// Externally stored block-chain (on heap) for arbitrary bit-widths larger than what can be inlined for space optimization.
	ext: Unique<Block>
}

//// Similar to how `BigInt` works internally.
struct Block(u64);
```

The last days were very insightful to me as I tried to implement a decent quality library for exactly this use-case, however, I came to the conclusion that this is really really difficult to achieve with pleasant results.

**Comment by cuviper** [comment]
How arbitrary are you thinking of the bit widths?  Still powers of two, or truly anything?

For particular fixed sizes, I know of the [`bigint`](https://crates.io/crates/bigint) for `U128`, `U256`, and `U512`, but I don't have any experience with it.

> Should they only be inter-operable with same-bit-width integers?

I think that would be consistent with how Rust treats primitive integers.  Promotion rules can quickly get complicated, and make it harder to reason about performance.  Ideally, the bit size would be a type parameter, `FixedInt<N>`, but who knows when Rust will support that.

> The last days were very insightful to me as I tried to implement a decent quality library for exactly this use-case, however, I came to the conclusion that this is really really difficult to achieve with pleasant results.

Then I hope you'll understand that I'm not really interested in taking major new functionality in `num`, especially when it could exist perfectly well in its own crate.  I find it hard enough to give `num` the time it deserves already...

**Comment by Robbepop** [comment]
> How arbitrary are you thinking of the bit widths? Still powers of two, or truly anything?

Truely anything between `1` and `N` where `N` is dependent on the max buffer size on the actual machine. With space optimization one could design this `FixedInt` to be space optimized for any `N` smaller than or equal to `64` for example and use a simple `u64` to represent it. For certain bit-widths such as `8`, `16`, ..., `64` one could also design `FixInt` to fall back to the native implementation for maximum efficiency.

> I think that would be consistent with how Rust treats primitive integers. Promotion rules can quickly get complicated, and make it harder to reason about performance. Ideally, the bit size would be a type parameter, FixedInt<N>, but who knows when Rust will support that.

In my design I wouldn't want the bit-width to be a compile-time constant to allow to mix bit-widths at run-time. But this may just be due to my personal use-case. However, maybe two different implementations (one at compile-time and one at run-time) would be ideal!

> Then I hope you'll understand that I'm not really interested in taking major new functionality in num, especially when it could exist perfectly well in its own crate. I find it hard enough to give num the time it deserves already...

I can understand that. I was just hopeful that it would magically fit perfectly well into this crate.

As I have said I am currently trying extremely hard to create this data structure with more or less of success - at least I can tell that it is far harder than I thought initially ...

I can link a prototype implementation once I am fine with it if you are interested. :)

**Comment by cuviper** [comment]
> I can link a prototype implementation once I am fine with it if you are interested. :)

Please do!

**Comment by Robbepop** [comment]
Okay but this will take some time reiterating the design and implementation of an efficient implementation. Please be patient. I will update this issue once I am satisfied with the prototype. :)

**Comment by cuviper** [comment]
If you did this, or when you do, please do share that link.

**Comment by Robbepop** [comment]
@cuviper https://github.com/Robbepop/apint

I am still heavily iterating on the general design of the crate and currently do a lot of refactoring of some out dated parts. The current implementation is highly unstable, unfinished and not yet sufficiently tested.
