### ISSUE TITLE
Storing from_str_radix error into an enum

### ISSUE THREAD

**Issue by spease** [rust-num/num#331]
I was trying to do the following:
```
fn parse_integer<T: num::Integer>(&mut self) -> Result<T> {
  T::from_str_radix(self.parse_token()?.as_ref(), 10).map_err(Error::ParseIntError)
}
```

The problem is that there doesn't seem to be any way to specify "T" such that the return type can be proven to be one type - so the compiler balks. FromStrRadixError is generic so I can't easily put it on Error, but ParseIntError cannot be proven.

**Comment by cuviper** [comment]
Perhaps add `where T: num::Num<FromStrRadixError = ParseIntError>`?

**Comment by spease** [comment]
Thanks, that works. I had tried an alternative way of specifying that, but I got an error:

```
error: equality constraints are not yet supported in where clauses (#20041)
   --> src/lvm.rs:435:67
    |
435 |   fn parse_integer<T: num::Integer>(&mut self) -> Result<T> where T::FromStrRadixErr = std::num::ParseIntError {
```

**Comment by cuviper** [comment]
OK, I think there's nothing for num to change here, so I'm closing this.  Please reopen if that's not correct!

**Comment by spease** [comment]
Yup
