### ISSUE TITLE
num_derive for newtypes

### ISSUE THREAD

**Issue by gnzlbg** [rust-num/num#341]
Say I want to implement some num traits for:

```rust
struct R64(f64);
```

Is there a macro in `num_derive` to do this? Currently FromPrimitive and ToPrimitive only work on enums.

**Comment by cuviper** [comment]
Those `FromPrimitive` and `ToPrimitive` derivations for enums are all we have right now.  I would be fine with adding newtype derivations though!

**Comment by termoshtt** [comment]
I think proc_macro is better.
I've created a NewType derivation in [my crate](https://github.com/termoshtt/procedurals#newtype) which derives `From`, `Deref`, and `DerefMut`. IMO, `#[derive(Num)]` should derive `Add`, `Sub`, `Mul`, `Div`, and `Rem` which is required by `NumOps` (not `Num`). Remaining traits, i.e. `One` and `Zero` should be separated. Hence the interface becomes:

```rust
#[derive(One, Zero, Num, PartialEq)]
struct R64(f64);
```

What do you think?

**Comment by gnzlbg** [comment]
I am writing a `derive_ops` crate where you can do this:

```rust
#[derive(stdops)]
#[unary_ops(Not, Neg, Deref, ...)]
#[binary_ops(Add = "Self", Add = "f64", Index = "usize)]
struct R64(f64);
```

to specify exactly what you want to derive.

It then builds on this to support ops groups:

```rust
[derive(stdops)]
[numops]
[binary_ops(DivAssign = "Self")]
struct R64(f64);
```

If you want I can commit it and maybe we can collaborate. The idea is to derive all ops in `stdops` for tuple structs with one element easily.

**Comment by termoshtt** [comment]
It looks great :)
Does it work on stable rust? I think it will be an independet crate since it will be useful in several cases.

**Comment by gnzlbg** [comment]
It works on stable rust (uses only custom derive). Yes I intended it as a separate crate because I think it is generally useful.

**Comment by gnzlbg** [comment]
`derive_more` doesn't support deriving Add<R64> for R64 by design. It only supports Add<f64> for f64.

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-derive#1
