### ISSUE TITLE
Add rsqrt method to Float trait

### ISSUE THREAD

**Issue by davll** [rust-num/num#343]
`rsqrt` is a widely used math function in game development, and is faster than combining the two functions: `recip(sqrt(x))` thanks to x86 SSE instructions `RSQRTSS`, `RSQRTPS`, `RSQRTSD`, and `RSQRTPD`. Should we consider add `rsqrt` to `Float` trait?

- x86/x86_64 SSE: [_mm_rsqrt_ps](https://msdn.microsoft.com/en-us/library/22hfsh53(v=vs.90).aspx) (note that RSQRT instruction is approximate, less accurate than SQRT)
- ARM Neon [VRSQRTE](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0489g/CIHDIACI.html)
- PowerPC Altivec: vec_rsqrte

**Comment by cuviper** [comment]
This should probably be proposed for the standard library first.  So far we don't have any arch-specific code -- I'd rather just have num's `impl Float for f64` forward to an optimized/intrinsic call in `std`.

**Comment by clarcharr** [comment]
I agree; it makes sense to offer this in libstd.

**Comment by davll** [comment]
Reasonable, I'll propose it in `rust-lang/rust`.
I'll keep the issue open as reminder.

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-traits#1
