### ISSUE TITLE
pow for BigInt?

### ISSUE THREAD

**Issue by alankemp** [rust-num/num#344]
In this issue https://github.com/rust-num/num/issues/264 the solution was to use num::pow for BigInts.

This doesn't seem to work, it generates the error:
error[E0277]: the trait bound `std::option::Option<num::BigInt>: num::One` is not satisfied

I guess this is related to the work discussed here https://github.com/rust-num/num/issues/214 (adding is_one to the One trait).

Am I going something wrong, or is this broken at the moment?

https://play.rust-lang.org/?gist=d4db09361467fc0d86ccd0fba85e2bfe&version=stable

    extern crate num;
    use num::pow;
    use num::bigint::{ BigInt, ToBigInt };

    fn main() 
    {
        let x = 2.to_bigint();
    
        let y = pow(x, 15);
    
        println!("{} {}", x, y);
    }

**Comment by cuviper** [comment]
`to_bigint` returns an `Option`, as it could theoretically fail for some types. You'll have to `match` or `unwrap()` that first, or use an infallible conversion like `BigInt::from(2)`.

**Comment by alankemp** [comment]
Sorry, I missed that.  Thanks for your help.
