### ISSUE TITLE
Implement T::consts::Pi etc.

### ISSUE THREAD

**Issue by venkatarun95** [rust-num/num#361]
It would be great if this crate could implement constants such as PI, e etc. just as in f32::consts::PI

**Comment by cuviper** [comment]
Have you seen [`FloatConst`](https://docs.rs/num-traits/0.1.42/num_traits/float/trait.FloatConst.html)?

**Comment by venkatarun95** [comment]
I did not. Thanks. Is it compatible with this library's Float type?

Also, is there a way to convert literals to Float objects?

**Comment by cuviper** [comment]
`Float` and `FloatConst` are traits, primarily implemented by the standard `f32` and `f64` types. There's nothing to convert -- if you have a generic function with something like `T: Float`, then either of the normal floats will work.

**Comment by venkatarun95** [comment]
Sorry if this is a very basic question. I am new to Rust. Suppose I want to write a function that multiplies by 1.45 (an arbitrary number) as follows:

fn mult<T: Float>(a: T) -> T {
  a * 1.45
}

Can I implement this? What if 1.45 is a standard constant like PI and I want the highest supported precision?

If this is possible, if you think it is a good idea, I'll submit a pull request to the documentation, since I couldn't figure it out.

Thanks again

**Comment by cuviper** [comment]
Note that 1.45 is imprecise in binary floating point, so you probably should make sure to start with `f64` to reduce error.  `f64` is the default type inferred for floating point literals, but it's better to be explicit, especially when type conversions are involved.

For multiplying with a literal, `Float` includes `NumCast`, so you can write `T::from(1.45f64)` -- which returns an `Option`, so maybe also use `.unwrap()`.

For standard constants, use `T: Float + FloatConst` and then you can write `T::PI()`.

**Comment by venkatarun95** [comment]
Thanks a lot!
