### ISSUE TITLE
Functions to distinguish signaling from non-signaling NaN's

### ISSUE THREAD

**Issue by icefoxen** [rust-num/num#364]
It'd be nice to be able to distinguish signaling from non-signaling NaN's in some cases.  In particular, writing a WebAssembly interpreter; WebAssembly disallows signaling NaN's, so one needs some way to detect and filter them out.  Easy to do with bit masks, but it would be nice to be a little more abstract.

Thank you!

**Comment by cuviper** [comment]
`FloatCore` or `Float::integer_decode` can also help safely get the mantissa, if you're on a pre-1.20 Rust without `to_bits()`.  You still have to know where to find that `is_quiet` bit though.

I'm not sure if there's a good way we can add a method for this without a breaking change.  Standalone methods aren't really in the spirit of num-traits.  A whole new trait for this would be possible, but seems rather excessive.

**Comment by icefoxen** [comment]
I was imagining it just being a method on the `Float` trait, really. Not sure if that would count as a breaking change though, since implementors of `Float` would need to add a method. Honestly maybe this belongs in std instead...

**Comment by cuviper** [comment]
> Not sure if that would count as a breaking change though, since implementors of Float would need to add a method.

Yes, that makes it breaking, unless we also add a default implementation for that method, but I don't know if that's possible here.

**Comment by icefoxen** [comment]
The obvious default implementation is "return false", but that's not really a *correct* default implementation, just a stub.

Due to that, and the fact that it is deathly platform-dependent, I think it might fit better in `std`.  Might be something to consider for inclusion in `num` if/when you want to break the API anyway though.

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-traits#51
