### ISSUE TITLE
Thank you for 0.2.0. #thankyou

### ISSUE THREAD

**Issue by inv2004** [rust-num/num#370]
Thank you for 0.2.0.
Looks like the new version of num helped to move my k-nucleotide benchmark to the first Rust-place (4 total):

https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/knucleotide-rust-8.html

**Comment by cuviper** [comment]
Cool!  It looks like you're only using `num::{FromPrimitive, ToPrimitive}`, but if those little bits helped you out, I'm glad to hear it. :smile:

**Comment by cuviper** [comment]
@Silur, I don't put much emphasis on what the raw version number means.
