### ISSUE TITLE
RealOps or something like that.

### ISSUE THREAD

**Issue by quadrupleslap** [rust-num/num#373]
Sometimes it's hard to provide constructors for `One` and `Zero` because the constructors require additional state. In cases like that, it'd still be useful if either `Real` didn't depend on `One` and `Zero`, or there was a separate `RealOps` trait that didn't depend on them.

Edit: Also, I guess the other constructors in `Real` would also have to not be there.

**Comment by cuviper** [comment]
Do you have a concrete example of a type with such stateful constructors?

**Comment by quadrupleslap** [comment]
In my case, reverse mode AD needs each number to have a reference to a tape. But now that I think about it, generic math without being able to construct numbers is pretty useless, so I think just removing the constructors is a pretty stupid idea. Sorry about that!
