### ISSUE TITLE
[Question] Power BigInt with BigInt Exponent

### ISSUE THREAD

**Issue by cupcakearmy** [rust-num/num#379]
Hi, I have a question :)

How do you power a BigInt to a BigInt power? 

```rust
use num::pow::pow;
use num::BigInt;
use num::FromPrimitive;

let p = pow(BigInt::from(2), 3);
```

But what if I don't want to power by `3` but another BigInt? basically:

```rust
use num::pow::pow;
use num::BigInt;
use num::FromPrimitive;

let p = pow(BigInt::from(2), BigInt::from(3)); // Nope ❌
```

Maybe I am missing something. I looked at the similar issues, but could not find an answer.

**Comment by rbolog** [comment]
The _exp_ should be type usize

`let p = pow(BigInt::from(2), 3 as usize);`

**Comment by cuviper** [comment]
Right, the plain `pow` function only takes a `usize` exponent. The `Pow` trait is more flexible, but for integers this is only implemented for unsigned exponents. So there is `Pow<BigUint> for BigInt`, but not `Pow<BigInt>`.

**Comment by cupcakearmy** [comment]
I now understand that powering BigInts is not very simple. `modpow` is supported so at least in my use case it was enough :) Feel free to close the issue

**Comment by ActuallyHappening** [comment]
So the summary is, if you need to do exponentiation with `BigInt`s, use an exponent of type `BigUint`
