### ISSUE TITLE
No way to take signed powers of BigRational

### ISSUE THREAD

**Issue by itaibn** [rust-num/num#380]
Upon encountering it in my code, I noticed that since BigInt does not implement Pow<u32>, the Ratio::pow method does not exist for the type BigRational, and so as far as I can tell there's no library method for taking a signed power of a bignum rational. I notice that BigInt doesn't have any Pow implementation, which might be deliberate since checked_pow is preferred, but leaves a gap in the BigRational API.

**Comment by cuviper** [comment]
See rust-num/num-bigint#106 -- next time we make breaking changes, we should clean that up. In the meantime, I will close this issue as a duplicate. Thanks!
