### ISSUE TITLE
Is there a trait that represents a real number?

### ISSUE THREAD

**Issue by vandenheuvel** [rust-num/num#388]
I am looking for a trait that allows me to abstract over a number type that is either a Float or a fractional number. In num-traits I found a trait that only covers Float types, while in num-rational I didn't find a trait for the rational numbers, only a struct.

Would it be useful to have a trait type that covers both, like [this](https://docs.rs/math_traits/0.2.1/math_traits/real/trait.Real.html)?

**Comment by cuviper** [comment]
There is a [`Real` in num-traits](https://docs.rs/num-traits/0.2.11/num_traits/real/trait.Real.html), a bit looser than `Float`:

> A trait for real number types that do not necessarily have floating-point-specific characteristics such as NaN and infinity.

 We don't have the capability in num-rational to implement `num_traits::Real` nor the one from `math_traits`, because we don't have transcendental methods like `sqrt`. What operations do you actually want from such a trait?

**Comment by vandenheuvel** [comment]
I would like to encode constraints like finiteness and "not NaN-ness" in the type system. Both a `Ratio` type and custom float-based type would then implement the trait I am looking for.

I currently have something like this:
```rust
pub trait RealField: OrderedField + DedekindComplete {
    fn ceil(self) -> Self;
    fn floor(self) -> Self;
    ...

    fn zero() -> Self {
        Self::additive_identity()
    }
    fn one() -> Self {
        Self::multiplicative_identity()
    }
}

pub trait OrderedField: Ord + Field {}
pub trait DedekindComplete {}

pub trait Field:
    Eq
        + Add<Output = Self> + AddAssign
        + Sub<Output = Self> + SubAssign
        + Neg<Output = Self>
        + Mul<Output = Self> + MulAssign
        + Div<Output = Self> + DivAssign
{
    fn additive_identity() -> Self;
    fn multiplicative_identity() -> Self;
}

```

**Comment by cuviper** [comment]
It seems to me that you might be looking for a different level of mathematical precision than what `num` provides. For example, you've separated `Field::addititive_identity` and `RealField::zero`, but here we just have `Zero` and call it the additive identity.

**Comment by vandenheuvel** [comment]
You might be right, I think that this falls outside the scope of this crate.

One can even wonder whether it makes sense to define such a trait at all, as I don't think an implementation of `RealField` that sticks to the contract completely is possible.
