### ISSUE TITLE
Take down outdated sub-crate docs

### ISSUE THREAD

**Issue by camsteffen** [rust-num/num#390]
A google search led me to these obsolete docs unwittingly. Shouldn't they be taken down?

https://rust-num.github.io/num/rand/index.html

The above link is for the `rand` crate but I believe there may be other sub-crates that have been split off.

**Comment by camsteffen** [comment]
FWIW, a reproducible google search is "rust thread_rng".

**Comment by cuviper** [comment]
I think at first I intended to set up redirects to docs.rs, but then I simply forgot about it. What do you think, should I just kill the `gh-pages` branch altogether?

**Comment by camsteffen** [comment]
You're asking me? 😃 If it's all redundant with docs.rs then yes.

**Comment by cuviper** [comment]
I've saved the branch as `old-gh-pages` _just in case_, but the old docs are now 404.
