### ISSUE TITLE
Additional primitive type wrappers

### ISSUE THREAD

**Issue by RazrFalcon** [rust-num/num#394]
(not sure how to properly call it)

I'm looking for additional [std::num](https://doc.rust-lang.org/stable/std/num/index.html) types like:

- NonZeroF32 (without memory layout optimization)
- NonZeroF64 (without memory layout optimization)
- PositiveNumber<T>
- NegativeNumber<T>
- NormalizedF32, NormalizedF64 (aka 0.0...1.0)
- Range (not an iterator)

Is there are plans on making something like this?

**Comment by cuviper** [comment]
There are no plans, and note that we don't even do anything for the existing `NonZero*` integers. They don't really act like integers -- apart from formatting and comparison, they don't even implement any operators.

So I think this is out of scope for `num`, but I encourage you to explore the idea in your own crate!

**Comment by RazrFalcon** [comment]
I see, thanks.
