### ISSUE TITLE
Blanket implementation of Signed for &T

### ISSUE THREAD

**Issue by stijnfrishert** [rust-num/num#402]
I was wondering if it were possible to impl Signed for &T

Nothing complex, but would make my life using trait bound and iters a lot easier.

**Comment by cuviper** [comment]
In general, it's a breaking change to add a blanket implementation.

In this instance, `Signed` requires `Neg<Output = Self>` as well as `Num` that also has `Self` outputs. The implication is that `&T: Signed` would have to be able to produce other `Self = &T` outputs, which isn't generally possible.

**Comment by cuviper** [comment]
Closing since it's not really possible, but feel free to ask any followup questions.
