### ISSUE TITLE
Extended GCD on BigUint doesn't work

### ISSUE THREAD

**Issue by mhogrefe** [rust-num/num#418]
```
use num::{BigUint, Integer, One};

fn main() {
    BigUint::one().extended_gcd(&BigUint::one());
}
```
fails with
`thread 'main' panicked at 'Cannot subtract b from a because b is larger than a.'`

Maybe the implementation should be specific to `BigInt` rather than being part of the `Integer` trait?

**Comment by cuviper** [comment]
Yeah, I regret not making that require `Signed` -- see rust-num/num-integer#40.

It's still useful in the `Integer` trait for other signed integer types, like `i32`.

**Comment by mhogrefe** [comment]
Thanks for responding! That makes sense. I'll close this since it's a dupe.
