### ISSUE TITLE
Yank pre-Rust 1.0.0 versions

### ISSUE THREAD

**Issue by kornelski** [rust-num/num#420]
I'm trying to compile crates with `-Z minimal-versions`, but num 0.1 is one of the crates that often gets pulled in, and won't compile due to being written for a prehistoric 0.x Rust version.

Could you yank all the releases older than Rust 1.0.0?

This should do it:

```bash
for v in 0.0.1 0.0.2 0.0.3 0.0.4 0.0.5 0.0.6 0.1.0 0.1.1 0.1.10 0.1.11 0.1.12 0.1.13 0.1.14 0.1.15 0.1.16 0.1.17 0.1.18 0.1.19 0.1.2 0.1.20 0.1.21 0.1.22 0.1.23 0.1.24 0.1.25 0.1.3 0.1.4 0.1.5 0.1.6 0.1.7 0.1.8 0.1.9; do
    cargo yank --vers "$v"
done
```

**Comment by cuviper** [comment]
It looks like the main gap is commit 3ccb4bd6c5cfaa8287fb19bd2c4ebbdfb9d77025 that fixed things for [RFC 1214](https://rust-lang.github.io/rfcs/1214-projections-lifetimes-and-wf.html), which took effect as an error in [Rust 1.7](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-170-2016-03-03). That commit is in 0.1.27, which also still builds in Rust 1.0.0 (if you don't enable "bigint"->"rand"), so I think it's fine to yank before that. This is also visible on docs.rs, which failed to build 0.1.26 and earlier.

It's done, hope that helps!
