### ISSUE TITLE
New API additions in num-complex 0.4.2 not configurable through num version

### ISSUE THREAD

**Issue by mwlon** [rust-num/num#426]
`num-complex` added the trait `ComplexFloat` in 0.4.2. It is unfortunate that one can only require this version of `num-complex` by adding a dependency on `num-complex` directly. It would be nicer if `num` had a `0.4.2` version that included these new API changes.

See https://github.com/apache/arrow-rs/issues/3849 and https://github.com/apache/arrow-rs/pull/4482 for more context.

**Comment by cuviper** [comment]
I just published `num 0.4.1` depending on the latest of each sub-crate.

**Comment by mwlon** [comment]
Started https://github.com/apache/arrow-rs/pull/4532 to bring this full circle
