### ISSUE TITLE
Updating dependencies: num-traits

### ISSUE THREAD

**Issue by saona-raimundo** [rust-num/num#433]
` num v0.4.1` depends on ` num-traits v0.2.15`, but `num-traits v0.2.18` is published and contains 
[num_traits::identities::ConstOne](https://docs.rs/num-traits/0.2.18/num_traits/identities/trait.ConstOne.html)
and
[num_traits::identities::ConstZero](https://docs.rs/num-traits/0.2.18/num_traits/identities/trait.ConstZero.html)

Could we update the dependency? 

# Use case

This relates to dnsl48/fraction#104, where we want to implement these traits for the crate `fraction`.
Updating the dependencies of `num` avoids adding `num-traits` as a direct dependency.

# Related issues

#406

**Comment by cuviper** [comment]
Published num v0.4.2!
