### ISSUE TITLE
pow should not be a uint

### ISSUE THREAD

**Issue by steveklabnik** [rust-num/num#56]
https://github.com/rust-lang/rust/issues/16755

**Comment by lfairy** [comment]
`pow()` uses `u32` now: https://github.com/rust-num/num/blob/516587ce2e0819d250e2c170e8d72333453f1c3a/src/traits.rs#L844

Should we close this issue?

**Comment by hauleth** [comment]
Absolutely.

**Comment by vks** [comment]
`num::pow` and `num::checked_pow` still use `uint` for the exponent. Changing it to `u32` would be a breaking change though.
