### ISSUE TITLE
`std::num::Checked{Add,Sub,Mul,Div}` should have type parameters

### ISSUE THREAD

**Issue by steveklabnik** [rust-num/num#59]
<a href="https://github.com/lifthrasiir"><img src="https://avatars.githubusercontent.com/u/323836?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lifthrasiir](https://github.com/lifthrasiir)**
_Monday Apr 14, 2014 at 12:33 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/13510_

_This issue was labelled with: A-libs in the Rust repository_

---

The corresponding `std::ops` traits have both the type of right hand side operand and the type of result, while `Checked*` traits do not (and always assume that both operands and result have the same type). There is no real reason to make `Checked*` traits behave differently from `std::ops` traits, and having them as is hampers advanced uses of operator overloading: for example, if the scalar type (e.g. `DateTime`) and difference type (e.g. `Duration`) are distinct from each other then the current scheme wouldn't work at all.

**Comment by clarcharr** [comment]
Adding onto this, there should be checked versions of `Rem`, `Shl`, and `Shr` as well.

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-traits#15
