### ISSUE TITLE
All bit twiddling functions in num::traits::PrimInt should take or return usize instead of u32

### ISSUE THREAD

**Issue by octurion** [rust-num/num#80]
The trait `num::traits::PrimInt` mandates that any type implementing it must also implement `Shl<usize, Output=Self>` and `Shr<usize, Output=Self>` (in other words, `PrimInt` mandates that the shift amount be of type `usize`).

Thus all bit twiddling functions (`trailing_zeros`, `rotate_left`, `count_zeros` etc.) in `PrimInt` should take or return a `usize` instead of `u32` as the number of bits for the sake of consistency with what the implementation restrictions on `Shl` and `Shr` mandate.

**Comment by gnzlbg** [comment]
The problem is that the methods on primitive types like `rotate_left` expect an `u32` and that cannot be changed anymore (that ship has sailed). 

Maybe it would be better to require `Shl<u32, Output=Self>` and `Shr<u32, Output=Self>` instead. What do you think?

**Comment by gnzlbg** [comment]
I've implemented this and some other bit wise algorithms in PrimInt.

**Comment by cuviper** [comment]
I think changing the trait bounds to `u32` sounds fine, but it will be a breaking change, which I want to be pretty conservative about.  I should start a list somewhere of "things to break" so we can plan to do them all at once.

**Comment by cuviper** [comment]
This issue was moved to rust-num/num-traits#14
