### ISSUE TITLE
BitInt naming?

### ISSUE THREAD

**Issue by kkimdev** [rust-num/num#90]
I'd argue that `BigInt` is not a precise name, since it's not necessarily big. If it's saying it's designed for representing big integers, well, `i64` is pretty big too. I don't have a good suggestion, but `BigInt` is like calling `std::Vec` big array.

**Comment by jhod0** [comment]
`BigInt` is a pretty standard name for arbitrary-precision arithmetic. Java, for example, had `java.math.BigInteger`, clojure has `clojure.lang.BigInt`, and perl has the `bigint` package.

**Comment by gifnksm** [comment]
When I originally added `BigInt` to `libextra`, I named the struct after D's `std.bigint.BigInt`. I didn't research other language's naming, but as @jhod0 pointed out, `BigInt` is not uncommon naming.

**Comment by cuviper** [comment]
If someone wants to offer better names for a very breaking change, go ahead, but the paint on this bikeshed has long since dried...
