### ISSUE TITLE
Numeric types should probably support "reference overloads" for operators.

### ISSUE THREAD

**Issue by sellibitze** [rust-num/num#94]
Writing generic code over numeric types is hard in Rust right now. One has to add additional bounds like Clone, Copy or a whole bunch of `for<'a> &'a T: for <'b> Add<&'b T, Output=T>` bounds (for various combinations of references, non-references and operators) to support "non-consuming" versions of arithmetic operators.

What do you guys and gals think about adding those "non-consuming operators" to the `Num` trait? I added these kinds of operator implementations for the built-in types in the standard library for that reason in consultation with @aturon . Addings these requirements to the `Num` trait would make the life of a numeric type provider a little harder but we still have macros that ease the pain. It would be a great benefit for generic numeric code in that "T: Num" is much less noisy than "T: Num + for<'b> Add<&'b T, Output=T> + …` etc.

**Comment by cuviper** [comment]
I hesitate to expand to requirements on `Num`, but maybe a new `RefNum`?

```rust
/// Numeric types with operators by reference
pub trait RefNum
where for<'b> Self: Num + Add<&'b Self, Output=Self> // ...
, for<'a, 'b> &'a Self: Add<Self, Output=Self> + Add<&'b Self, Output=Self> // ...
{ }

// Implement it automatically for qualifying types
impl<T> RefNum for T
where for<'b> T: Num + Add<&'b T, Output=T> // ...
, for<'a, 'b> &'a T: Add<T, Output=T> + Add<&'b T, Output=T> // ...
{ }

// example use:
fn foo<T: RefNum>() -> T { T::zero() + &T::one() }
```

But my lifetimes are missing something here -- 1.3 is ok, but 1.4 warns:

```
warning: the trait `for<'a> core::ops::Add<T>` is not implemented for the type `&'a T` [E0277]
fn foo<T: RefNum>() -> T { T::zero() + &T::one() }
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
help: run `rustc --explain E0277` to see a detailed explanation
note: this warning results from recent bug fixes and clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details.
fn foo<T: RefNum>() -> T { T::zero() + &T::one() }
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: required by `traits::RefNum`
warning: the trait `for<'b, 'a> core::ops::Add<&'b T>` is not implemented for the type `&'a T` [E0277]
fn foo<T: RefNum>() -> T { T::zero() + &T::one() }
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
help: run `rustc --explain E0277` to see a detailed explanation
note: this warning results from recent bug fixes and clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details.
fn foo<T: RefNum>() -> T { T::zero() + &T::one() }
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: required by `traits::RefNum`
```

That's [RFC 1214](https://github.com/rust-lang/rfcs/blob/master/text/1214-projections-lifetimes-and-wf.md).  I tinkered with it briefly, but couldn't make this happy yet...

**Comment by andersk** [comment]
Here’s a way to get reasonably close.

```rust
pub trait NumOps<RHS = Self, Output = Self>: Sized
    + Add<RHS, Output = Output> + Sub<RHS, Output = Output>
    + Mul<RHS, Output = Output> + Div<RHS, Output = Output>
    + Rem<RHS, Output = Output> {}
impl<RHS, Output, T: Sized
     + Add<RHS, Output = Output> + Sub<RHS, Output = Output>
     + Mul<RHS, Output = Output> + Div<RHS, Output = Output>
     + Rem<RHS, Output = Output>> NumOps<RHS, Output> for T {}

pub trait RefNum: Num + for<'a> NumOps<&'a Self> {}
impl<T: Num + for<'a> NumOps<&'a T>> RefNum for T {}

pub trait DerefNum<Base>: NumOps<Base, Base> + for<'a> NumOps<&'a Base, Base> {}
impl<Base, T: NumOps<Base, Base> + for<'a> NumOps<&'a Base, Base>> DerefNum<Base> for T {}
```

The existing bound on `Num` may be also abbreviated as `PartialEq + Zero + One + NumOps`. Demo:

```rust
fn foo<T: RefNum>() -> T { T::zero() + &T::one() }
fn bar<T: RefNum>() -> T where for<'a> &'a T: DerefNum<T> { &T::zero() + T::one() }
fn baz<T: RefNum>() -> T where for<'a> &'a T: DerefNum<T> { &T::zero() + &T::one() }
let _: (i32, i32, i32) = (foo(), bar(), baz());
```

I was not able to make either of `T: RefNum` or `for<'a> &'a T: DerefNum<T>` automatically imply each other, so functions need to ask for both. That may be a compiler bug. Still, I would find this useful enough.

**Comment by cuviper** [comment]
We have reference traits since #283.
